[memory_usage]
disabled = false
threshold = 50

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "


[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "0"
time_range = "08:00:00-17:00:00"

[conda]
format = "[$symbol$environment](dimmed green) "
ignore_base = false
